# .readthedocs.yaml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

python:

  install:
    # 1) install your package in “editable” mode so Sphinx can import it
    - method: pip
      path: .
      extra_requirements: [docs]

sphinx:
  # where your conf.py lives
  configuration: docs/source/conf.py
