# .readthedocs.yaml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"

python:
  # pick any supported version; e.g. 3.10, 3.11, 3.12…
  version: 3.10

  install:
    # 1) install your package in “editable” mode so Sphinx can import it
    - method: pip
      path: .[docs]

sphinx:
  # where your conf.py lives
  configuration: docs/source/conf.py
