name: Publish (Trusted Publisher)

on:
  push:
    tags:
      - "v*.*.*"      # tag like v0.1.0

jobs:
  build-and-publish-testpypi:
    name: Publish to TestPyPI
    permissions:
      id-token: write   # required for OIDC
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build sdist and wheel
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/